name: R Installation

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Install_R: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install R
        run sudo apt-get install -y r-base
